#!/usr/bin/env bash
# gen_secrets.sh - mint the swarm's shared secrets into a gitignored header.
#
# Two secrets live here - a plaintext literal in tracked source would also be
# recoverable with `strings` from any built binary:
#   OTA key   - the only thing standing between a LAN attacker and arbitrary firmware
#   PMK/LMK   - ESP-NOW encryption; shared by all six nodes
# The TLS private key is separate (main/certs/, also gitignored).
#
# Run once. The output is main/secrets.h, which .gitignore excludes. Keep a copy
# somewhere safe: losing it means every node needs a USB reflash to rejoin.
set -euo pipefail
umask 077   # secrets.h must never exist world-readable, not even briefly
OUT="$(dirname "$0")/../firmware/eth/main/secrets.h"

if [ -f "$OUT" ] && [ "${1:-}" != "--force" ]; then
  echo "$OUT already exists. Re-running mints NEW keys and orphans every node"
  echo "still running the old ones. Use --force if that is really what you want."
  exit 1
fi

hexbytes() { openssl rand -hex "$1" | sed 's/\(..\)/0x\1, /g' | sed 's/, $//'; }

cat > "$OUT" <<HDR
/* GENERATED by tools/gen_secrets.sh on $(date -u +%Y-%m-%dT%H:%MZ) - DO NOT COMMIT.
 * .gitignore excludes this file. It is also baked into every binary, so the
 * build artifacts are secret-bearing too (the build directories are gitignored for that reason).
 *
 * Rotating these is a FLAG DAY: ESP-NOW peers that disagree on the keys cannot
 * hear each other at all, so all six nodes must be updated in one sitting. */
#pragma once

/* the /ota door on 8443 */
#define BOHUN_OTA_KEY "$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"

/* ESP-NOW primary + local master keys, 16 bytes each */
#define BOHUN_PMK { $(hexbytes 16) }
#define BOHUN_LMK { $(hexbytes 16) }

/* Deployment addressing - EDIT BY HAND for your LAN: the mask's reserved
 * address (must sit outside your DHCP pool) and your gateway. The values
 * below are documentation placeholders and route nowhere. */
#define BOHUN_MASK_IP "192.0.2.2"
#define BOHUN_MASK_GW "192.0.2.1"

/* Home WiFi for the observers' touch-opened OTA window - fill these in BY
 * HAND; the generator will not guess your network. Empty = window off. */
#define BOHUN_WIFI_SSID ""
#define BOHUN_WIFI_PASS ""
HDR
chmod 600 "$OUT"   # belt; the umask above is the braces
echo "minted $OUT"
echo
# Print the RECIPE, not the key: the literal would otherwise land in terminal
# scrollback and shell history - the exact exposure this script exists to end.
echo "export this so the deploy tools can reach the node:"
cat <<'RECIPE'
  export BOHUN_OTA_KEY=$(grep BOHUN_OTA_KEY firmware/eth/main/secrets.h | cut -d'"' -f2)
RECIPE
